default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: proyectosoftware_development
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: proyectosoftware_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
#default: &default
#  adapter: postgresql
#  encoding: unicode
#  host: localhost
 # port: 5433
  #username: postgres
  #password: postgres
  #pool: 5
  